week7/carbbook/urls.py
from django.conf.urls.defaults import *

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    # Example:
    (r'^recipes/$', 'recipes.views.index'),
    (r'^recipes/(?P<recipe_id>\d+)/$', 'recipes.views.detail'),
    (r'^recipes/category/$', 'recipes.views.category'),
    (r'^recipes/search/$', 'recipes.views.search'),
    (r'^recipes/search-form/$', 'recipes.views.search_form'),
    # Uncomment the admin/doc line below to enable admin documentation:
    (r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    (r'^admin/', include(admin.site.urls)),
)

week7/carbbook/recipes/models.py
from django.db import models

class Recipe(models.Model):
	CATEGORY_CHOICES = (
		('Breakfast', 'Breakfast'),
		('Lunch', 'Lunch'),
		('Snack', 'Snack'),
		('Dinner', 'Dinner'),
		('Dessert', 'Dessert'),
	)
	name = models.CharField(max_length=30)
	category = models.CharField(max_length=10, choices=CATEGORY_CHOICES)
	protein = models.IntegerField()
	net_carbs = models.IntegerField()
	def __unicode__(self):
                return self.name	

class Ingredient(models.Model):
	SIZE_CHOICES = (
        	('C', 'Cup(s)'),
        	('Tbs', 'Tablespoon(s)'),
		('Tsp', 'Teaspoon(s)'),
		('None', 'None'),
	)
	recipe = models.ForeignKey(Recipe)
	name = models.CharField(max_length=20)
	amount = models.IntegerField()
	size = models.CharField(max_length=10, choices=SIZE_CHOICES)

week7/carbbook/recipes/views.py
from django.db.models import Q
from django.template import Context, loader
from django.http import HttpResponse, Http404
from recipes.models import Recipe
from django.shortcuts import render_to_response

def search_form(request):
    return render_to_response('recipe/search_form.html')

def search(request):
    if 'q' in request.GET and request.GET['q']:
        q = request.GET['q']
        recipes = Recipe.objects.filter(name__icontains=q)
        return render_to_response('recipe/search_results.html',
            {'recipes': recipes, 'query': q})
    else:
        return HttpResponse('Please submit a search term.')


def index(request):
	recipe_list = Recipe.objects.all()
	t = loader.get_template('recipe/index.html')
	c = Context({'recipe_list': recipe_list})
	return HttpResponse(t.render(c))

def category(request, category_name):
	recipe_list = Recipe.objects.filter(category=category_name)
	t = loader.get_template('recipe/category.html')
	c = Context({'recipe_list': recipe_list})
	return HttpResponse(t.render(c))

def detail(request, recipe_id):
	try:
		r = Recipe.objects.get(pk=recipe_id)
	except Recipe.DoesNotExist:
		raise Http404
	return render_to_response('recipe/detail.html', {'recipe': r})

week7/carbbook/templates/recipe/category.html
<head> <title>Recipe List</title> </head>

<span style="font-size: 24pt;">Recipe List</span>

<a href="/recipes/">Go Back to Index</a>

<table style="border-collapse: collapse; width: 100%;">
  <tbody>
    <tr>
      <td style="border: 2px solid black;"><span style="font-size: 14pt;">Recipe Name</span><br /></td>
      <td style="border: 2px solid black;"><span style="font-size: 14pt;">Category</span><br /></td>
      <td style="border: 2px solid black;"><span style="font-size: 14pt;">Net Carbs</span><br /></td>
      <td style="border: 2px solid black;"><span style="font-size: 14pt;">Protein</span><br /></td>
    </tr><tr>

{% if recipe_list %}
    <ul>
    {% for recipe in recipe_list %}
      <td style="border: 2px solid black;"><a href="/recipes/{{ recipe.id }}/">{{ recipe.name }}</a><br />
        </td>
      <td style="border: 2px solid black;"><a href="/recipes/category/{{ recipe.category }}/">{{ recipe.category }}<br />
        </td>
      <td style="border: 2px solid black;">{{ recipe.net_carbs }}<br />
        </td>
      <td style="border: 2px solid black;">{{ recipe.protein }}<br />
        </td>
    </tr>
    {% endfor %}
    </ul>
{% else %}
    <p>No recipes are available.</p>
{% endif %}

    </tr>
  </tbody>
</table>

week7/carbbook/templates/recipe/detail.html
<h1>{{ recipe.name }}</h1>

<ul>
{% for ingredient in recipe.ingredient_set.all %}
    <li>{{ ingredient.amount}} {{ ingredient.size }} {{ ingredient.name }}</li>
{% endfor %}
</ul>


<a href=/recipes/>Back to Index</a>

week7/carbbook/templates/recipe/index.html
<head> <title>Recipe List</title>

<style type="text/css">
<!--
body {margin: 0; padding: 0; font: normal 82% sans-serif; background-image: url(blocksbg1.jpg); background-attachment: fixed;}
h1 {margin: 0; margin-bottom: 0px; padding: 8px; color: #ffffff; background-image: url(laptop1.jpg); background-color: #0066FF;}
.tagline {font-size: 60%; color: #ffffff;}

#search {float: right; width: 280px; padding: 5px; text-align: right;}
.button {border: outset; 2px #000000; background-color: #00CCFF; color: #ffffff; font-weight: bold;}
.text {border: solid 1px #000000; background-color: #eeeeee;}

#bread {margin-top: 0px; margin-bottom: 10px; padding: 5px; border-top: solid 1px #000000; border-bottom: solid 1px #000000; background-color: #00CCFF; text-align: right;}
#bread a {margin-left: 2px; margin-right: 2px; color: #000000; text-decoration: none;}
#bread a:hover {text-decoration: underline;}

#left {float: left; width: 18%; border: solid 1px #cccccc; margin-bottom: 15px; background-color: #ffffff; border-top: 0;}
#left ul {list-style: none; margin: 0; padding: 0;}
#left li {margin: 0px; padding: 0px;}
#left a {display: block; width: 95.5%; margin: 0px; padding: 2px; border: solid 1px #ffffff; color: #0066cc; text-decoration: none;}
#left a:hover {border: solid 1px #0066cc; background-color: #0066cc; color: #ffffff;}
#left h3 {margin: 0; padding: 2px; font-weight: normal; background-color: #FFCCFF; border-top: solid 1px #000000; border-bottom: solid 1px #000000;}

#content {margin-left: 20%; padding: 0; border-left: solid 1px #cccccc; border-top: 0; border-bottom: solid 1px #ffffff;  background-color: #ffffff;}
#content h3 {margin: 0; padding: 2px; font-weight: normal; background-color: #FFCCFF; border-top: solid 1px #000000; border-bottom: solid 1px #000000;}
#content p {margin: 5px; color: #000000;}
#content a {color: #0066cc; text-decoration: none;}
#content a:hover {color: #0000ff; text-decoration: underline;}
#content .point {margin: 3%; padding: 0px; border: solid 1px #000000; border-top: 0; background-color: #f9f9f9;}
#content .point h3 {}
#content .code {margin: 3%; padding: 7px; border: solid 1px #cccccc; background-color: #eeeeee; font: normal 100% courier; color: #000000;}

#footer {clear: both; margin-top: 0px; padding: 5px; border: solid 1px #cccccc; background-color: #0066FF;}
#footer p {float: left; margin: 0;}
#footer h5 {margin: 0; text-align: right; color: #000000;}
#footer a {margin-left: 2px; margin-right: 2px; color: #000000; text-decoration: none;}
#footer a:hover {text-decoration: underline;}

table.sample {
	border-width: 4px;
	border-spacing: 2px;
	border-style: ridge;
	border-color: gray;
	border-collapse: separate;
	background-color: rgb(250, 240, 230);
	width: 100%;
}
table.sample th {
	border-width: 1px;
	padding: 2px;
	border-style: inset;
	border-color: red;
	background-color: rgb(250, 240, 230);
	-moz-border-radius: 6px 6px 6px 6px;
}
table.sample td {
	border-width: 1px;
	padding: 2px;
	border-style: inset;
	border-color: red;
	background-color: rgb(250, 240, 230);
	-moz-border-radius: 6px 6px 6px 6px;
}

-->
</style>
</head>

<body>
    <div id="search">
	<form action="/recipes/search/" method="get">
        <input type="text" class="text" name="q"/>
        <input type="button" value="Search" class="button" />
	</form>
    </div>

<h1>Recipe List <span class="tagline">"Main Index" ::.</span></h1>
<div id="bread">&#091;
<a href="#">Home</a>&#093;&nbsp;&#091;<a href="#">Link 1</a>&#093;&nbsp;&#091;<a href="#">Link 2 </a>&#093;&nbsp;&#091;<a href="#">Link 3</a>&#093;
</div>

<span style="font-size: 24pt;">Recipe List</span>

<div id="content">

<table class="sample">
  <tbody>
    <tr>
      <td style="border: 2px solid black;"><span style="font-size: 14pt;">Recipe Name</span><br /></td>
      <td style="border: 2px solid black;"><span style="font-size: 14pt;">Category</span><br /></td>
      <td style="border: 2px solid black;"><span style="font-size: 14pt;">Net Carbs</span><br /></td>
      <td style="border: 2px solid black;"><span style="font-size: 14pt;">Protein</span><br /></td>
    </tr><tr>

{% if recipe_list %}
    <ul>
    {% for recipe in recipe_list %}
      <td style="border: 2px solid black;"><a href="/recipes/{{ recipe.id }}/">{{ recipe.name }}</a><br />
        </td>
      <td style="border: 2px solid black;"><a href="/recipes/category/{{ recipe.category }}/">{{ recipe.category }}<br />
        </td>
      <td style="border: 2px solid black;">{{ recipe.net_carbs }}<br />
        </td>
      <td style="border: 2px solid black;">{{ recipe.protein }}<br />
        </td>
    </tr>
    {% endfor %}
    </ul>
{% else %}
    <p>No recipes are available.</p>
{% endif %}

    </tr>
  </tbody>
</table>
</div>
<div id="footer">
<p>Contact  ::&#091;<a href="#">jeff at mindcloud dot com</a>&#093;</p>
<h5>Heading 5</h5>
</div>
</body>
</html>

week7/carbbook/templates/recipe/search_form.html
<html>
<head>
    <title>Recipe Search</title>
</head>
<body>
    <form action="/search/" method="get">
        <input type="text" name="q">
        <input type="submit" value="Search">
    </form>
</body>
</html>

week7/carbbook/templates/recipe/search_results.html
<p>You searched for: <strong>{{ query }}</strong></p>

{% if recipes %}
    <p>Found {{ recipes|length }} recipes{{ recipes|pluralize }}.</p>
    <ul>
        {% for recipe in recipes %}
        <li><a href="/recipes/{{ recipe.id }}/">{{ recipe.name }}</a><br /></li>
        {% endfor %}
    </ul>
{% else %}
    <p>No recipes matched your search criteria.</p>
{% endif %}